### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by nosslin579**
Detailed example of how to use ContextAwareCompletableFuture

### CODE REVIEW

**Comment by nosslin579** [comment]
Great to hear.

Ok, how many examples do you see?

First there is the regular propagation to common thread 1
Then there is a uncertain example with continuation to common thread 2 (not sure we should keep that one)
Then there is an example where it does not propagate.

Maybe we should add example to show where context is removed.

**Comment by sjoerdtalsma** [comment]
I would start with the most simple example:
- Show that `runAsync` / `supplyAsync` propagates an existing context value to a background thread.
This is the most important part of the entire library.

Next, document the existence of 'followup-actions' implemented by the various `CompletionStage` methods and show that by default, the context also propagates into these methods (synchronous or asynchronous).

Lastly, show that even modifications in the Context propagate from one completion stage into the next (only after #53 is merged)

**Comment by sjoerdtalsma** [comment]
The examples should be kept as brief as possible (just 1 or 2 lines ideally) to focus on the behaviour.

**Comment by sjoerdtalsma** [comment]
Try to separate the different things you're trying to describe.
Maybe we could even create separate PRs for adding each case to the documentation.
You could take a look at https://github.com/talsma-ict/context-propagation/blob/develop/context-propagation-java8/src/test/java/nl/talsmasoftware/context/futures/ContextAwareCompletableFutureTest.java for inspiration on what is possible..

**Comment by sjoerdtalsma** [comment]
Closing this, since #82 was merged

**Pull request closed without merging**
